project_id = "papajohns-demo-420321"
region     = "us-central1"
gke_cluster_name = "pjdemo-cluster-1"
vpc_name = "pjdemo-vpc"
subnet_name = "pjdemo-subnet01"

# project_id = "___gcp_project_id___"
# region     = "___gcp_region___"
# gke_cluster_name = "___gke_cluster_name___"
# vpc_name = "___vpc_name___"
# subnet_name = "___subnet_name___"