project_id = "ardent-strategy-420320"
region     = "us-central1"
gke_cluster_name = "gke-cluster-1234"
vpc_name = "vpc-1234"
subnet_name = "subnet-1234"

# project_id = "___gcp_project_id___"
# region     = "___gcp_region___"
# gke_cluster_name = "___gke_cluster_name___"
# vpc_name = "___vpc_name___"
# subnet_name = "___subnet_name___"